# Generated by Django 4.1.2 on 2022-10-16 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
